### PR TITLE
support MACKEREL_HOST_STATUS_ON_START env

### PR DESCRIPTION
**Pull request by astj**
documented at https://mackerel.io/ja/docs/entry/howto/container-agent (Sorry, English translation for this param is not available!)

### CODE REVIEW

**Comment by aereal** [comment]
@astj You are now collaborator of this repository, so you can merge this as a collaborator 🎉

**Comment by astj** [comment]
Thank you!!

**Comment by aereal** [comment]
@astj Do you have NPM account? I'll invite you to the NPM package collaborator.

**Comment by astj** [comment]
@aereal Currently I don't have NPM account, as far as I remember

**Pull request merged**
